import axios from 'axios'

const PINATA_API_KEY = import.meta.env.VITE_PINATA_API_KEY
const PINATA_SECRET_KEY = import.meta.env.VITE_PINATA_SECRET_API_KEY

if (!PINATA_API_KEY || !PINATA_SECRET_KEY) {
  console.warn('Pinata credentials not configured. Using mock IPFS storage.')
}

const PINATA_BASE_URL = 'https://api.pinata.cloud'
const PINATA_GATEWAY = 'https://gateway.pinata.cloud/ipfs'

export const ipfsService = {
  /**
   * Upload audio file to IPFS via Pinata
   * @param {File|Blob} audioFile - Audio file to upload
   * @param {Object} metadata - Additional metadata
   * @returns {Promise<Object>} IPFS hash and URL
   */
  async uploadAudioFile(audioFile, metadata = {}) {
    if (!PINATA_API_KEY || !PINATA_SECRET_KEY) {
      return this.mockUploadAudioFile(audioFile, metadata)
    }

    try {
      const formData = new FormData()
      
      // Create a unique filename
      const timestamp = Date.now()
      const filename = `pocket-rights-audio-${timestamp}.wav`
      
      formData.append('file', audioFile, filename)
      
      // Add metadata
      const pinataMetadata = {
        name: filename,
        keyvalues: {
          app: 'pocket-rights',
          type: 'audio-recording',
          timestamp: new Date().toISOString(),
          ...metadata
        }
      }
      
      formData.append('pinataMetadata', JSON.stringify(pinataMetadata))
      
      const response = await axios.post(
        `${PINATA_BASE_URL}/pinning/pinFileToIPFS`,
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data',
            'pinata_api_key': PINATA_API_KEY,
            'pinata_secret_api_key': PINATA_SECRET_KEY
          }
        }
      )

      const ipfsHash = response.data.IpfsHash
      const ipfsUrl = `${PINATA_GATEWAY}/${ipfsHash}`

      return {
        success: true,
        ipfsHash,
        ipfsUrl,
        filename,
        size: audioFile.size,
        timestamp: new Date().toISOString()
      }
    } catch (error) {
      console.error('IPFS upload error:', error)
      // Fallback to mock for development
      return this.mockUploadAudioFile(audioFile, metadata)
    }
  },

  /**
   * Upload incident documentation to IPFS
   * @param {Object} incidentData - Complete incident data
   * @returns {Promise<Object>} IPFS hash and URL
   */
  async uploadIncidentDocument(incidentData) {
    if (!PINATA_API_KEY || !PINATA_SECRET_KEY) {
      return this.mockUploadIncidentDocument(incidentData)
    }

    try {
      // Create a comprehensive incident document
      const document = {
        ...incidentData,
        documentType: 'pocket-rights-incident',
        version: '1.0',
        createdAt: new Date().toISOString(),
        app: 'Pocket Rights',
        disclaimer: 'This document was generated by Pocket Rights app for documentation purposes only.'
      }

      const response = await axios.post(
        `${PINATA_BASE_URL}/pinning/pinJSONToIPFS`,
        document,
        {
          headers: {
            'Content-Type': 'application/json',
            'pinata_api_key': PINATA_API_KEY,
            'pinata_secret_api_key': PINATA_SECRET_KEY
          }
        }
      )

      const ipfsHash = response.data.IpfsHash
      const ipfsUrl = `${PINATA_GATEWAY}/${ipfsHash}`

      return {
        success: true,
        ipfsHash,
        ipfsUrl,
        documentId: incidentData.id || incidentData.incidentId,
        timestamp: new Date().toISOString()
      }
    } catch (error) {
      console.error('IPFS document upload error:', error)
      return this.mockUploadIncidentDocument(incidentData)
    }
  },

  /**
   * Create shareable incident card and upload to IPFS
   * @param {Object} incident - Incident data
   * @param {Object} location - Location data
   * @param {string} audioIpfsHash - IPFS hash of audio file
   * @returns {Promise<Object>} Shareable card data
   */
  async createShareableIncidentCard(incident, location, audioIpfsHash = null) {
    const cardData = {
      title: 'Police Interaction Documentation',
      timestamp: incident.timestamp,
      location: {
        address: location.formattedAddress || 'Location recorded',
        coordinates: location.coordinates || null
      },
      incident: {
        id: incident.id || incident.incidentId,
        notes: incident.notes || '',
        duration: 'Audio recording available',
        sharedWithContacts: incident.sharedWithContacts || false
      },
      audio: audioIpfsHash ? {
        ipfsHash: audioIpfsHash,
        url: `${PINATA_GATEWAY}/${audioIpfsHash}`,
        available: true
      } : {
        available: false,
        note: 'Audio not uploaded to IPFS'
      },
      rights: {
        reminder: 'Know Your Rights information was available during this interaction',
        disclaimer: 'This documentation is for informational purposes only and does not constitute legal advice.'
      },
      metadata: {
        app: 'Pocket Rights',
        version: '1.0',
        createdAt: new Date().toISOString(),
        documentType: 'incident-card'
      }
    }

    return this.uploadIncidentDocument(cardData)
  },

  /**
   * Retrieve file from IPFS
   * @param {string} ipfsHash - IPFS hash
   * @returns {Promise<Object>} File data
   */
  async retrieveFile(ipfsHash) {
    try {
      const response = await axios.get(`${PINATA_GATEWAY}/${ipfsHash}`)
      return {
        success: true,
        data: response.data,
        contentType: response.headers['content-type']
      }
    } catch (error) {
      console.error('IPFS retrieval error:', error)
      return {
        success: false,
        error: error.message
      }
    }
  },

  /**
   * Get file metadata from Pinata
   * @param {string} ipfsHash - IPFS hash
   * @returns {Promise<Object>} File metadata
   */
  async getFileMetadata(ipfsHash) {
    if (!PINATA_API_KEY || !PINATA_SECRET_KEY) {
      return this.mockGetFileMetadata(ipfsHash)
    }

    try {
      const response = await axios.get(
        `${PINATA_BASE_URL}/data/pinList?hashContains=${ipfsHash}`,
        {
          headers: {
            'pinata_api_key': PINATA_API_KEY,
            'pinata_secret_api_key': PINATA_SECRET_KEY
          }
        }
      )

      const pinData = response.data.rows[0]
      if (!pinData) {
        throw new Error('File not found')
      }

      return {
        success: true,
        ipfsHash: pinData.ipfs_pin_hash,
        size: pinData.size,
        timestamp: pinData.date_pinned,
        metadata: pinData.metadata
      }
    } catch (error) {
      console.error('Error getting file metadata:', error)
      return this.mockGetFileMetadata(ipfsHash)
    }
  },

  /**
   * Unpin file from Pinata (remove from IPFS)
   * @param {string} ipfsHash - IPFS hash to unpin
   * @returns {Promise<Object>} Unpin result
   */
  async unpinFile(ipfsHash) {
    if (!PINATA_API_KEY || !PINATA_SECRET_KEY) {
      console.log('Mock unpin file:', ipfsHash)
      return { success: true, unpinned: true }
    }

    try {
      await axios.delete(
        `${PINATA_BASE_URL}/pinning/unpin/${ipfsHash}`,
        {
          headers: {
            'pinata_api_key': PINATA_API_KEY,
            'pinata_secret_api_key': PINATA_SECRET_KEY
          }
        }
      )

      return {
        success: true,
        unpinned: true,
        ipfsHash
      }
    } catch (error) {
      console.error('Error unpinning file:', error)
      return {
        success: false,
        error: error.message
      }
    }
  },

  /**
   * List all pinned files for the account
   * @param {Object} filters - Optional filters
   * @returns {Promise<Array>} List of pinned files
   */
  async listPinnedFiles(filters = {}) {
    if (!PINATA_API_KEY || !PINATA_SECRET_KEY) {
      return this.mockListPinnedFiles()
    }

    try {
      const params = new URLSearchParams()
      
      if (filters.status) params.append('status', filters.status)
      if (filters.pageLimit) params.append('pageLimit', filters.pageLimit)
      if (filters.pageOffset) params.append('pageOffset', filters.pageOffset)
      
      const response = await axios.get(
        `${PINATA_BASE_URL}/data/pinList?${params.toString()}`,
        {
          headers: {
            'pinata_api_key': PINATA_API_KEY,
            'pinata_secret_api_key': PINATA_SECRET_KEY
          }
        }
      )

      return response.data.rows.map(pin => ({
        ipfsHash: pin.ipfs_pin_hash,
        size: pin.size,
        timestamp: pin.date_pinned,
        metadata: pin.metadata,
        url: `${PINATA_GATEWAY}/${pin.ipfs_pin_hash}`
      }))
    } catch (error) {
      console.error('Error listing pinned files:', error)
      return this.mockListPinnedFiles()
    }
  },

  /**
   * Generate shareable URL for incident
   * @param {string} ipfsHash - IPFS hash of incident document
   * @returns {string} Shareable URL
   */
  generateShareableUrl(ipfsHash) {
    // Create a user-friendly URL that redirects to IPFS
    const baseUrl = window.location.origin
    return `${baseUrl}/incident/${ipfsHash}`
  },

  /**
   * Mock functions for development
   */
  async mockUploadAudioFile(audioFile, metadata) {
    console.log('Mock IPFS audio upload:', { size: audioFile.size, metadata })
    
    // Simulate upload delay
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    const mockHash = 'Qm' + Math.random().toString(36).substring(2, 48)
    
    return {
      success: true,
      ipfsHash: mockHash,
      ipfsUrl: `https://ipfs.io/ipfs/${mockHash}`,
      filename: `mock-audio-${Date.now()}.wav`,
      size: audioFile.size,
      timestamp: new Date().toISOString()
    }
  },

  async mockUploadIncidentDocument(incidentData) {
    console.log('Mock IPFS document upload:', incidentData)
    
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    const mockHash = 'Qm' + Math.random().toString(36).substring(2, 48)
    
    return {
      success: true,
      ipfsHash: mockHash,
      ipfsUrl: `https://ipfs.io/ipfs/${mockHash}`,
      documentId: incidentData.id || incidentData.incidentId,
      timestamp: new Date().toISOString()
    }
  },

  mockGetFileMetadata(ipfsHash) {
    return {
      success: true,
      ipfsHash,
      size: Math.floor(Math.random() * 1000000),
      timestamp: new Date().toISOString(),
      metadata: {
        name: `mock-file-${Date.now()}`,
        app: 'pocket-rights'
      }
    }
  },

  mockListPinnedFiles() {
    const mockFiles = []
    for (let i = 0; i < 5; i++) {
      const mockHash = 'Qm' + Math.random().toString(36).substring(2, 48)
      mockFiles.push({
        ipfsHash: mockHash,
        size: Math.floor(Math.random() * 1000000),
        timestamp: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
        metadata: {
          name: `mock-file-${i}`,
          app: 'pocket-rights'
        },
        url: `https://ipfs.io/ipfs/${mockHash}`
      })
    }
    return mockFiles
  },

  /**
   * Validate IPFS hash format
   * @param {string} hash - IPFS hash to validate
   * @returns {boolean} Is valid IPFS hash
   */
  isValidIpfsHash(hash) {
    // Basic IPFS hash validation (CIDv0 and CIDv1)
    const cidv0Regex = /^Qm[1-9A-HJ-NP-Za-km-z]{44}$/
    const cidv1Regex = /^[a-z2-7]{59}$/
    
    return cidv0Regex.test(hash) || cidv1Regex.test(hash)
  },

  /**
   * Get IPFS gateway URL
   * @param {string} ipfsHash - IPFS hash
   * @param {string} gateway - Optional custom gateway
   * @returns {string} Gateway URL
   */
  getGatewayUrl(ipfsHash, gateway = PINATA_GATEWAY) {
    return `${gateway}/${ipfsHash}`
  }
}

// Configuration and setup information
export const IPFS_CONFIG = {
  PINATA_BASE_URL,
  PINATA_GATEWAY,
  SUPPORTED_AUDIO_FORMATS: ['audio/wav', 'audio/mp3', 'audio/ogg', 'audio/webm'],
  MAX_FILE_SIZE: 100 * 1024 * 1024, // 100MB
  REQUIRED_ENV_VARS: [
    'VITE_PINATA_API_KEY',
    'VITE_PINATA_SECRET_API_KEY'
  ]
}
