import React, { useState } from 'react'
import { Share2, Save, Trash2, Download, Send } from 'lucide-react'
import { useUser } from '../contexts/UserContext'

const IncidentSummaryCard = ({ incident, onSave, onDiscard, variant = 'shareable' }) => {
  const [notes, setNotes] = useState('')
  const [sharing, setSharing] = useState(false)
  const { emergencyContacts } = useUser()

  const handleSave = () => {
    onSave({
      notes,
      sharedWithContacts: sharing
    })
  }

  const handleShare = async () => {
    const incidentData = {
      timestamp: new Date(incident.timestamp).toLocaleString(),
      location: incident.location,
      notes: notes || 'No additional notes'
    }
    
    const shareText = `Incident Documentation
Time: ${incidentData.timestamp}
Location: ${incidentData.location}
Notes: ${incidentData.notes}

Generated by Pocket Rights - Your legal rights, instantly accessible.`

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Incident Documentation',
          text: shareText
        })
      } catch (err) {
        // Fallback to clipboard
        navigator.clipboard.writeText(shareText)
        alert('Incident details copied to clipboard')
      }
    } else {
      navigator.clipboard.writeText(shareText)
      alert('Incident details copied to clipboard')
    }
  }

  const sendToEmergencyContacts = () => {
    // In production, this would send SMS via Twilio
    alert(`Alert sent to ${emergencyContacts.length} emergency contacts`)
    setSharing(true)
  }

  return (
    <div className="card max-w-lg mx-auto">
      <div className="flex justify-between items-start mb-4">
        <div>
          <h3 className="text-lg font-semibold text-textPrimary">Incident Documentation</h3>
          <p className="text-sm text-textSecondary">
            {new Date(incident.timestamp).toLocaleString()}
          </p>
        </div>
        <div className="flex space-x-2">
          <button
            onClick={handleShare}
            className="p-2 hover:bg-gray-100 rounded-md transition-colors"
            title="Share incident"
          >
            <Share2 className="h-4 w-4 text-textSecondary" />
          </button>
          <button
            onClick={onDiscard}
            className="p-2 hover:bg-red-50 rounded-md transition-colors"
            title="Discard recording"
          >
            <Trash2 className="h-4 w-4 text-red-500" />
          </button>
        </div>
      </div>

      <div className="space-y-4">
        <div>
          <label className="text-sm font-medium text-textPrimary">Location</label>
          <p className="text-sm text-textSecondary mt-1">{incident.location}</p>
        </div>

        <div>
          <label className="text-sm font-medium text-textPrimary">Recording</label>
          <div className="mt-1 flex items-center space-x-2">
            {incident.audioUrl && (
              <audio controls className="w-full">
                <source src={incident.audioUrl} type="audio/wav" />
                Your browser does not support audio playback.
              </audio>
            )}
          </div>
        </div>

        <div>
          <label htmlFor="notes" className="text-sm font-medium text-textPrimary">
            Additional Notes
          </label>
          <textarea
            id="notes"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="mt-1 w-full input h-20 resize-none"
            placeholder="Add any additional details about the incident..."
          />
        </div>

        {emergencyContacts.length > 0 && (
          <div>
            <label className="text-sm font-medium text-textPrimary">Emergency Alerts</label>
            <div className="mt-2 space-y-2">
              <button
                onClick={sendToEmergencyContacts}
                className="flex items-center space-x-2 w-full p-3 bg-red-50 hover:bg-red-100 rounded-md transition-colors"
              >
                <Send className="h-4 w-4 text-red-600" />
                <span className="text-sm text-red-700">
                  Alert {emergencyContacts.length} emergency contact{emergencyContacts.length !== 1 ? 's' : ''}
                </span>
              </button>
              {sharing && (
                <p className="text-xs text-accent">✓ Emergency contacts have been notified</p>
              )}
            </div>
          </div>
        )}

        <div className="flex space-x-3 pt-4">
          <button
            onClick={handleSave}
            className="flex-1 btn-primary flex items-center justify-center space-x-2"
          >
            <Save className="h-4 w-4" />
            <span>Save Incident</span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default IncidentSummaryCard